apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cicd-demo.fullname" . }}-config
  labels:
    {{- include "cicd-demo.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  PYTHONPATH: "/app/src"
  PYTHONUNBUFFERED: "1"
